### ISSUE TITLE
Turbine models for 40m blade

### ISSUE THREAD

**Issue by windpower2023** [NREL/openfast-turbine-models#12]
Thanks for uploading turbine models for different sizes. Could you please also upload the turbine model for a 40ish m blade like GE 1.6, V82 or SWT-2.3-82?

**Comment by ewquon** [comment]
Thank you for your interest. However, we currently have no plans to release open-source models of those turbines. Given that these are older turbines, it is more challenging to apply the inverse design process that we used for the other more modern turbines.
