### ISSUE TITLE
Structural layout of the NREL-2.8-127 blade seems physically inconsistent

### ISSUE THREAD

**Issue by davidovitch** [NREL/openfast-turbine-models#15]
I am trying to run a HAWC2 version of the `NREL-2.8-127` version using the in-development HAWC2 WindIO converter. We're doing this for upcoming work in the AWAKEN/JAM/MERIDIONAL projects. Since the 6x6 stiffness matrix is missing from the windIO yaml file at DTU Wind we've tried to use the defined cross sections and run them through BECAS to recompute the full 6x6 stiffness matrix. According to our understanding the blade structural layout looks like this (view from top, black lines are leading and trailing edge, red are the shear webs):
![structural_layout_topview](https://github.com/user-attachments/assets/b1ddbdb1-3dd4-4e22-9fd8-22f73cb69cb4)

Note shear webs and spar cap towards the tip move out of the blade.

Is it possible that the definition you have pushed here on Github is not your latest version?

This is a complex problem with many moving parts, happy to take a conference call to further clarify this issue or to discuss how to interpret this model correctly.

**Comment by fzahle** [comment]
it appears there may be a sign error in our code's interpretation of the `offset_y_pa`. the cap and webs should be offset towards the TE and not the LE. I'll look further into this, so for now, don't spend time checking for issues until I have had a further look at this.

**Comment by fzahle** [comment]
Indeed, there was a sign error in our code. But this then introduces another issue, now at the trailing edge. What I've done is to shorten the aft shear web so it stops at r/R=0.8. Is that consistent with what you do in WISDEM? I suspect maybe you have some consistency checking that fixes the issue of the web extending beyond the TE.

![nrel2p8_windiostructure](https://github.com/user-attachments/assets/fe434a53-1cf4-4c72-92c5-241827024d19)

Also, the `rotation` associated with the two shear webs' `offset_y_pa` should change sign and be opposite the sign of the twist. the two spar caps are defined correctly.

**Comment by ewquon** [comment]
Thank you for digging into this. @ptrbortolotti or @gbarter, could either of you comment?

**Comment by ptrbortolotti** [comment]
hey @fzahle and @davidovitch , good catch guys, WISDEM has some "robustness" built in, see https://github.com/WISDEM/WISDEM/blob/992076a14bf2f18defc1dd5be17e72c89e83431f/wisdem/glue_code/gc_WT_DataStruc.py#L1924, and so the inconsistency was not caught. stopping the web at 80% span sounds reasonable. @ewquon

As for the `rotation`, when it's locked to the aero twist, WISDEM does apply a minus sign. I guess we could report the rotation explicitly in terms of grid and values, like we do in the spar caps
