### ISSUE TITLE
NREL-2.3-107 Controller file

### ISSUE THREAD

**Issue by rhaghi** [NREL/openfast-turbine-models#7]
Hi,

I am trying to run sims for NREL-2.3-107, but it seems I am missing the DLL/SO file for the controller. 
Am I overlooking something?

**Comment by rhaghi** [comment]
OK, I managed to figure out the simulations need ROSCO in place. I installed ROSCO and found DLL/SO file; however, I am facing an error running the sims. This is the error:

`SolveOption2:SrvD_CalcOutput:DLL_controller_call:ROSCO:SetParameters:ReadControlParameterFileSub:
A fatal error occurred when parsing data from
NREL-2p3-107_DISCON.IN`

I am guessing the problem is ROSCO version, and I need a new IN file for the turbine. Would you mind sharing the controller tuning `ymal` file to rerun ROSCO with the latest version?

**Comment by ewquon** [comment]
Hi, thanks for your interest in these models. I'm glad you figured out the ROSCO dependency. The shortest path to getting a working model is to simply check out the version of ROSCO described in the DISCON.IN header, in this case: [version 2.2](https://github.com/NREL/ROSCO/releases/tag/v2.2.0). 

These files were generated using WEIS, so unfortunately I do not have an input yaml for you. If you want to use the latest version of ROSCO, you can look at https://github.com/NREL/ROSCO/blob/main/Examples/ROSCO_walkthrough.ipynb — it will walk you through the YAML details, drawing on the examples in https://github.com/NREL/ROSCO/tree/main/Tune_Cases. 

Please note that this model has not been fully calibrated in terms of the structural response, so if you intend to do aeroservoelastic analysis, further model testing is strongly recommended. Good luck!
